# config_53.py
wandb_project = "wav2vec_26_6_5"
wandb_run = "cy_100-ug53"
preprocessing_only = False
resume = False
TRAINING_PARAMS = {
    "output_dir": "../weights/cy_100-xlsr-ug53", 
    "overwrite_output_dir":True,        
    "num_train_epochs": 800,                                    
    "per_device_train_batch_size": 32,
    "gradient_accumulation_steps": 1,
    "learning_rate": 1e-5,
    "lr_scheduler_type":"constant",
    "weight_decay":0.0,
    "warmup_steps":0,
    "max_grad_norm": 1.5,
    "save_steps": 800,                                         
    "save_total_limit": 5,
    "gradient_checkpointing": True,                              
    "fp16": True,                                              
    "eval_steps": 800,
    "logging_steps": 50,
    "evaluation_strategy": "steps",
    "load_best_model_at_end": False,
    "dataloader_num_workers": 8,
    "dataloader_pin_memory": True,
    "group_by_length": True,
    "report_to": ["wandb"],
    "remove_unused_columns": False,
    "ignore_data_skip": False,
    "ddp_find_unused_parameters": False,
    "deepspeed": "../ds_config/ds_config_zero2.json",
}
MODEL_PARAMS = {
    "output_dir": "../weights/cy_100-xlsr-ug53", 
    "model_name_or_path" : "/mnt/storage/qisheng/github/wav2vec_test/weights/ug_9000-xlsr-53_general_1e5/checkpoint-8000",
    "word_delimiter_token": "|",
    "unk_token": "[UNK]",
    "pad_token": "[PAD]",
    "feat_proj_dropout": 0.1,
    "attention_dropout": 0.1,
    "hidden_dropout": 0.1,
    "final_dropout": 0.1,
    "mask_time_prob": 0.1,
    "mask_time_length": 10,
    "mask_feature_prob": 0.1,
    "mask_feature_length": 10,
    "layerdrop": 0.0,
    "ctc_loss_reduction": "mean",
    "ctc_zero_infinity": False,
    "activation_dropout": 0.1,
    "add_adapter": False,
    "freeze_feature_encoder":True,
    "freeze_enc": True,
    "vocab_dir": "/mnt/storage/qisheng/github/wav2vec_test/weights/general_phoneme",
    "use_phoneme": True,
    "cache_dir":"/mnt/storage/ldl_linguistics/datasets",
}
DATASET_PARAMS = {
    "dataset_name" : "fsicoli/common_voice_22_0",
    "dataset_config_name" : "cy",
    "train_split" : "train",
    "test_split" : "test",
    "chars_to_ignore" : [',', '?', '.', '!', '-', ';', ':', "'"],
    "text_column":'sentence',
    "audio_column":'audio',
    "max_train_samples_per_language":[100],
    "max_eval_samples_per_language":[2704],
    "max_train_samples":None,
    "max_eval_samples":None,
    "max_duration_in_seconds":20.0,
    "min_duration_in_seconds":0.0,
    "preprocessing_num_workers":1,
    "eval_metrics" : ["wer"],
    "cache_dir":"/mnt/storage/ldl_linguistics/datasets",
}
